using Datafication.Core.Data;
using Datafication.Connectors.WebConnector.Connectors;
using Datafication.Sinks.Connectors.WebConnector;

Console.WriteLine("=== Datafication.WebConnector Screenshot Export Sample ===\n");

// First, extract some data to screenshot
var url = new Uri("https://quotes.toscrape.com/");
Console.WriteLine($"Source URL: {url}\n");

Console.WriteLine("1. Extracting quote data...");
var config = new CssSelectorConnectorConfiguration
{
    Source = url,
    Selector = ".quote",
    SubSelectors = new Dictionary<string, string>
    {
        { "Quote", ".text" },
        { "Author", ".author" },
        { "Tags", ".tags" }
    },
    IncludeInnerText = false,
    IncludeTagName = false,
    TrimValues = true
};

var connector = new CssSelectorConnector(config);
var data = await connector.GetDataAsync();
Console.WriteLine($"   Extracted {data.RowCount} quotes\n");

// 2. Basic screenshot using extension method
Console.WriteLine("2. Creating basic screenshot using extension method...");
var outputDir = Path.Combine(AppContext.BaseDirectory, "output");
Directory.CreateDirectory(outputDir);

var basicPath = Path.Combine(outputDir, "quotes_basic.png");
await data.ScreenshotToFileAsync(basicPath, rowLimit: 10, title: "Quotes to Scrape");
Console.WriteLine($"   Saved to: {basicPath}");
Console.WriteLine($"   File size: {new FileInfo(basicPath).Length:N0} bytes\n");

// 3. High resolution screenshot (2x scale)
Console.WriteLine("3. Creating high-resolution screenshot (2x)...");
var highResPath = Path.Combine(outputDir, "quotes_highres.png");
var highResBytes = await data.ScreenshotHighResAsync(rowLimit: 10, title: "High Resolution Export");
await File.WriteAllBytesAsync(highResPath, highResBytes);
Console.WriteLine($"   Saved to: {highResPath}");
Console.WriteLine($"   File size: {highResBytes.Length:N0} bytes\n");

// 4. JPEG format with quality setting
Console.WriteLine("4. Creating JPEG screenshot with quality setting...");
var jpegPath = Path.Combine(outputDir, "quotes_quality.jpg");
await data.ScreenshotToFileAsync(
    jpegPath,
    rowLimit: 10,
    title: "JPEG Export",
    format: ScreenshotFormat.Jpeg,
    quality: 85);
Console.WriteLine($"   Saved to: {jpegPath}");
Console.WriteLine($"   File size: {new FileInfo(jpegPath).Length:N0} bytes\n");

// 5. Using ScreenshotSink with custom configuration
Console.WriteLine("5. Creating screenshot with custom styling...");
var customSink = new ScreenshotSink
{
    RowLimit = 10,
    Title = "Custom Styled Report",
    Subtitle = "Generated by Datafication.WebConnector",
    Format = ScreenshotFormat.Png,
    ViewportWidth = 1400,
    BackgroundColor = "#f8f9fa",
    HeaderBackgroundColor = "#2c3e50",
    HeaderTextColor = "#ffffff",
    UseAlternateRowColor = true,
    DeviceScaleFactor = 1.5
};

var customBytes = await customSink.Transform(data);
var customPath = Path.Combine(outputDir, "quotes_custom.png");
await File.WriteAllBytesAsync(customPath, customBytes);
Console.WriteLine($"   Saved to: {customPath}");
Console.WriteLine($"   File size: {customBytes.Length:N0} bytes\n");

// 6. Screenshot with custom CSS
Console.WriteLine("6. Creating screenshot with custom CSS...");
var cssSink = new ScreenshotSink
{
    RowLimit = 10,
    Title = "Custom CSS Styling",
    CustomCss = @"
        body { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px; }
        .title { color: white; text-shadow: 2px 2px 4px rgba(0,0,0,0.3); }
        .subtitle { color: rgba(255,255,255,0.8); }
        table { border-radius: 12px; box-shadow: 0 10px 40px rgba(0,0,0,0.2); }
        th { background-color: #3d5a80 !important; }
        tr:hover td { background-color: #e8f4ff !important; }
        .row-count { color: rgba(255,255,255,0.7); }
    "
};

var cssBytes = await cssSink.Transform(data);
var cssPath = Path.Combine(outputDir, "quotes_css.png");
await File.WriteAllBytesAsync(cssPath, cssBytes);
Console.WriteLine($"   Saved to: {cssPath}");
Console.WriteLine($"   File size: {cssBytes.Length:N0} bytes\n");

// 7. Screenshot bytes in memory (no file)
Console.WriteLine("7. Creating screenshot in memory (no file)...");
var memoryBytes = await data.ScreenshotAsync(rowLimit: 5, title: "In-Memory Screenshot");
Console.WriteLine($"   Created {memoryBytes.Length:N0} bytes in memory");
Console.WriteLine($"   PNG signature check: {(memoryBytes[0] == 0x89 && memoryBytes[1] == 0x50 ? "Valid PNG" : "Unknown format")}\n");

// 8. Wide viewport for tables with many columns
Console.WriteLine("8. Creating wide viewport screenshot...");
var wideSink = new ScreenshotSink
{
    RowLimit = 10,
    Title = "Wide Viewport Export",
    ViewportWidth = 2000,  // Extra wide
    FullPage = true
};

var wideBytes = await wideSink.Transform(data);
var widePath = Path.Combine(outputDir, "quotes_wide.png");
await File.WriteAllBytesAsync(widePath, wideBytes);
Console.WriteLine($"   Saved to: {widePath}");
Console.WriteLine($"   File size: {wideBytes.Length:N0} bytes\n");

// 9. Row limit demonstration
Console.WriteLine("9. Demonstrating row limit options...");
var fullSink = new ScreenshotSink { RowLimit = 100, Title = "All Rows" };
var limitedSink = new ScreenshotSink { RowLimit = 3, Title = "Only 3 Rows" };

var fullBytes = await fullSink.Transform(data);
var limitedBytes = await limitedSink.Transform(data);

Console.WriteLine($"   Full (up to 100 rows): {fullBytes.Length:N0} bytes");
Console.WriteLine($"   Limited (3 rows): {limitedBytes.Length:N0} bytes\n");

// 10. Summary
Console.WriteLine("10. Summary of generated files:");
Console.WriteLine($"    Output directory: {outputDir}\n");

var files = Directory.GetFiles(outputDir, "quotes_*.*");
foreach (var file in files.OrderBy(f => f))
{
    var info = new FileInfo(file);
    Console.WriteLine($"    - {info.Name}: {info.Length:N0} bytes");
}

Console.WriteLine("\n=== Sample Complete ===");
Console.WriteLine($"\nGenerated {files.Length} screenshot files.");
Console.WriteLine($"View them at: {outputDir}");
